### ISSUE TITLE
Investigate & possibly fix the people search functionality

### ISSUE THREAD

**Issue by amprokop** [chhsinnovation/openopps-platform#13]
When clicking the people search page locally, I get an infinite spinner error. I have elasticsearch 5.6 installed via brew, but haven't investigated further, so this may very well be a simple config issue.

### Acceptance Criteria
There should be a documented path to getting the people search functionality working locally such that we can know how to get it working in production.

![image](https://user-images.githubusercontent.com/3781835/81504401-fcba6a80-92b6-11ea-8c2f-bb02f475050f.png)

**Comment by bmcorum** [comment]
@amprokop sounds like maybe the user index did not get created. If you have kibana installed you can use that to look at your indices. If you don't have kibana installed you can just use the elastic api to list your indices. If the user index is missing, you can run the application and then once authenticated do a get request to the reindex api endpoint (requires isAdmin permissions) and it should create your index and return the number of documents indexed. I probably should have added some better error handling so that if the index does not exist the API call returns something other than just 404 or add some client handling for the 404 so that page doesn't just spin.

**Comment by amprokop** [comment]
Thanks for the additional info, @bmcorum! Your advice is, as always, appreciated.
